<h1>Create New Task</h1>

<form action="savetask" method="POST">
  <div>
    <label for="name">Name</label><br>
    <input type="text" id="name" name="name" required>
  </div>

  <div>
    <label for="description">Description</label><br>
    <textarea id="description" name="description" rows="4" required></textarea>
  </div>

  <div>
    <label for="user">Username</label><br>
    <input type="text" id="user" name="user" required>
  </div>

  <button type="submit">Save</button>
</form>

<p>
  <a href="<?= WEB_ROOT ?>/home">
    Return
  </a>
</p>