<footer class="w-full py-16 flex flex-col items-center">
    <div class="flex flex-col sm:flex-row gap-4 sm:gap-8 text-white text-[10px] font-black uppercase tracking-[0.2em]">

        <a href="https://github.com/gregoridelrio"
            target="_blank"
            class="flex items-center gap-2 hover:opacity-70 transition">
            <img src="/web/images/GitHub_White.png" class="h-3 w-3" alt="GitHub">
            Gregoridelrio
        </a>

        <a href="https://github.com/clara-cdp"
            target="_blank"
            class="flex items-center gap-2 hover:opacity-70 transition">
            <img src="/web/images/GitHub_White.png" class="h-3 w-3" alt="GitHub">
            Clara-cdp
        </a>

        <a href="https://www.barcelonactiva.cat/es/itacademy"
            class="hover:text-teal-400 transition"
            target="_blank">
            IT ACADEMY @2026
        </a>
    </div>
</footer>