<footer class="w-full py-16 flex flex-col items-center">
    <div class="flex gap-8 text-white text-[10px] font-black uppercase tracking-[0.2em]">
        <span class="flex items-center gap-2">
            <img src="/web/images/GitHub_White.png" class="h-3 w-3" alt="GitHub">
            Gregoridelrio
        </span>
        <span class="flex items-center gap-2">
            <img src="/web/images/GitHub_White.png" class="h-3 w-3" alt="GitHub">
            Clara-cdp
        </span>
        <span>IT ACADEMY @2026</span>
    </div>
</footer>