<header class="w-full max-w-7xl mx-auto px-12 pt-12 pb-6">
    <div class="flex items-center justify-between">

        <div class="flex items-center">
            <img src="/web/images/taskomania.png"
                alt="Task-O-Mania Logo"
                class="h-20 w-auto transition-all duration-500 ease-out 
            hover:scale-110  hover:brightness-125  hover:saturate-200 ">
        </div>
    </div>
</header>