-- Important! Change my_database for the name of your db and execute the script at MySQL Workbech/PhpMyAdmin

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- change here
CREATE SCHEMA IF NOT EXISTS my_database DEFAULT CHARACTER SET utf8 ;
USE my_database ;

-- and here
CREATE TABLE IF NOT EXISTS my_database.TASK (
  idTASK INT NOT NULL AUTO_INCREMENT,
  task_title VARCHAR(45) NOT NULL,
  task_description VARCHAR(450) NULL,
  user_name VARCHAR(45) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finished_at TIMESTAMP NULL,
  task_state ENUM('pending', 'ongoing', 'finished') NOT NULL,
  PRIMARY KEY (idTASK))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;