<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
	<header>TASK-O-MANIA
		<hr>
	</header>

	<div class="wrapper">

		<?php echo $this->content(); ?>
	</div>
	<footer style='text-align:center' ;>
		<hr>Greogidelrio&clara-cdp @2026

	</footer>

</body>

</html>